### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by dbohdan** [sdegutis/immaculata#3]
There is no license information in `package.json` and no license file in the repository. Please add them.

**Comment by sdegutis** [comment]
Good idea. Recommendations?

**Comment by dbohdan** [comment]
:+1:  I think the MIT License is a good choice.

**Comment by sdegutis** [comment]
@dbohdan I changed it btw. Now a variant of MIT.

**Comment by dbohdan** [comment]
@sdegutis I'll share my opinion, since you have pinged me about this.

[Right now](https://github.com/sdegutis/imlib/commit/2d1270c16dd8b33f451ab6700720afe28006b1e9) your license says:

> * The facts be acknowledged at least implicitly by the Software users
  that the Blessed Virgin Mary, Mother of God, never sinned, from the moment
  of her conception to her natural death, according to the doctrine
  of the Immaculate Conception as defined in 1854 by the Catholic Church,
  that Jesus is truly and physically present in the Blessed Sacrament,
  and that the Second Vatican Council is a valid and binding council.

1. If this is going to be the license, I am not going to use your software because I cannot comply with it.

2. More importantly, this is a strategic mistake. Nonstandard licenses are bad for adoption, especially licenses not written or reviewed by a lawyer. (I am assuming yours hasn't been.) They prevent corporate use because they require corporate lawyers to vet the license, which corporations usually want to avoid. A license that requires the user to affirm the Catholic faith is especially bad because it will obviously raise a lot of personal objections, but also because it probably isn't going to be considered a free license by the [FSF](https://www.fsf.org/) or the [OSI](https://opensource.org/). You can contact either organization through its mailing lists and ask if you doubt me.

If you proceed with this license, I encourage you to add a note in the readme about its requirements. An early warning will save users who cannot or don't want to comply with it the time they would invest.

**Comment by sdegutis** [comment]
@dbohdan Thanks for the advice. I will ask if I can relicense it.
