### ISSUE TITLE
Dev-Server Live Updates

### ISSUE THREAD

**Issue by tcardlab** [sdegutis/immaculata#6]
Would be nice to have some sort of SSE or WS to manage Live Reloading or HMR.
Otherwise a template to integrate with existing HMR solutions (vite et al.) might be convenient.

For now I'm just reloading on window focus.

**Comment by sdegutis** [comment]
Thanks for the idea. I don't think it would work well as a built-in feature, but I do think it's reasonable to make sure the core code accomodates live code reloading. How has integration been with it so far? Any difficulties with it, particularly any that may benefit from a core change?
